ask_titaevskiy/ask/urls.py
from django.conf.urls import patterns, url
from ask import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^tag/(?P<tag_id>\d+)/$', views.tag_view, name='tag_view'),
    url(r'^(?P<question_id>\d+)/$', views.detail, name='detail'),
    url(r'^new_question/$', views.new_question, name='new_question'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^user_info/$', views.user_info, name='user_info'),
    url(r'^user_questions/(?P<user_id>\d+)/$', views.user_questions, name='user_questions'),
)

ask_titaevskiy/ask_titaevskiy/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ask_titaevskiy.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('ask.urls', namespace='ask')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

ask_titaevskiy/ask/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class UserManager(BaseUserManager):
    def create_user(self, username, email, password):
        if not username:
            raise ValueError('Users must have an username')

        if not email:
            raise ValueError('Users must have an email address')

        if not password:
            raise ValueError('Users must have a password')

        user = self.model(
            username=username,
            email=UserManager.normalize_email(email)
        )

        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, email, password):
        user = self.create_user(
            username,
            email,
            password
        )
        user.is_admin = True
        user.save()
        return user


class User(AbstractBaseUser):
    username = models.CharField(
        max_length=32,
        unique=True
    )
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True
    )
    register_date = models.DateTimeField(
        verbose_name="registration date",
        auto_now_add=True
    )
    avatar = models.ImageField(
        upload_to='avatar/%Y/%m/%d',
        null=True
    )
    rating = models.IntegerField(default=0)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'password']

    objects = UserManager()

# Large spike for admin
    @property
    def is_staff(self):
        return self.username == 'Gexogen'

    @property
    def is_superuser(self):
        return self.username == 'Gexogen'

    def has_module_perms(self, app_label):
        return self.username == 'Gexogen'

    def has_perm(self, perm, obj=None):
        return self.username == 'Gexogen'

    def get_full_name(self):
        return self.username

    def get_short_name(self):
        return self.username
# End of spike


class Tag(models.Model):
    name = models.CharField(max_length=20)

    def __unicode__(self):
        return self.name


class Question(models.Model):
    title = models.CharField(max_length=50)
    question = models.TextField()
    pub_date = models.DateTimeField(
        verbose_name="ask date",
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        related_name='questions',
        related_query_name='question'
    )
    tags = models.ManyToManyField(
        Tag,
        null=True,
        related_name='questions',
        related_query_name='question'
    )
    rating = models.IntegerField(default=0)
    views = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title


class Answer(models.Model):
    question = models.ForeignKey(
        Question,
        related_name='answers',
        related_query_name='answer'
    )
    answer = models.TextField()
    author = models.ForeignKey(
        User,
        related_name='answers',
        related_query_name='answer'
    )
    right_answer = models.BooleanField(
        verbose_name='Right',
        default=False
    )
    pub_date = models.DateTimeField(
        verbose_name="answer date",
        auto_now_add=True
    )
    rating = models.IntegerField(default=0)

    def __unicode__(self):
        return self.answer

ask_titaevskiy/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta content="text/html">
    
    <title>
    {% block title %} 
      Главная страница 
    {% endblock %}
    </title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="/jqcloud/jqcloud.css">
    <link rel="stylesheet" type="text/css" href="/mystyle.css">
    <link href="http://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css" type="text/css" rel="stylesheet">

    {% block include_css %}
    {% endblock %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body>
    <header class="navbar navbar-default navbar-static-top" role="banner">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/"> ASK Титаевский </a>
        </div>

        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li class="dropdown">
              <a href="" class="dropdown-toggle" data-toggle="dropdown" style="padding-top: 1px; padding-bottom: 1px;">
              {% if user.avatar %}
                <img src="{{ MEDIA_URL }}{{ user.avatar }}" width="48" height="48">
              {% else %}
                <img width="48" height="48">
              {% endif %}
                  {{ user.username }}
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'ask:user_questions' user.id %}"> Мои вопросы </a></li>
                <li><a href="{% url 'ask:user_info' %}"> Мои настройки </a></li>
                <li><a href="{% url 'ask:logout' %}"> Выход </a></li>
              </ul>
            </li>
          {% else %}
            <a href="{% url 'ask:signin' %}" type="button" class="btn btn-default navbar-btn"> Регистрация </a>
            <a href="{% url 'ask:login' %}" type="button" class="btn btn-default navbar-btn"> Войти </a>
          {% endif %}
        </ul>
      </div>
    </header>

    <div class="container">
      <div class="row">
        <div class="col-md-9">
        {% block content %}

        {% endblock %}
        </div> <!-- col-md-9 -->

        <div class="col-md-3">
          <div style="margin-bottom: 20px;">
            <a class="btn btn-large btn-block btn-success" href="{% url 'ask:new_question' %}"> Задать вопрос </a>
          </div>

          <div class="input-group" id="fast-search" style="margin-bottom: 20px;">
            <input type="text" class="form-control" placeholder="Поиск">
            <span class="input-group-btn">
              <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
            </span>
          </div>

          <div class="panel panel-default">
            <div class="panel-heading"> Популярные теги </div>
            <div class="panel-body" id="tagscloud" style="height: 300px;"></div>
          </div>

          <div class="panel panel-default">
            <div class="panel-heading"> Лучшие участники </div>
            <div class="list-group">
              {% include "popular_users.html" %}
            </div>
          </div>
        </div> <!-- col-md-3 -->
      </div> <!-- row -->
    </div> <!-- container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="http://code.jquery.com/ui/1.10.4/jquery-ui.min.js"></script>
    <script src="/bootstrap/js/bootstrap.min.js"></script>
    <script src="/jqcloud/jqcloud-1.0.4.min.js"></script>
    <script src="/myscript.js"></script>
    <script src="/tags.js"></script>

    {% block include_js %}
    {% endblock %}

  </body>
</html>

ask_titaevskiy/templates/detail.html
{% extends "base.html" %}

	{% block title %}
	    {{ quest.title }}
	{% endblock %}

	{% block content %}
		<div class="media">
			<a class="pull-left" href="{% url 'ask:user_questions' quest.author.id %}">
			{% if quest.author.avatar %}
              <img class="media-object" src="{{ MEDIA_URL }}{{ quest.author.avatar }}" width="64" height="64">
            {% else %}
              <img width="64" height="64">
            {% endif %}
			</a>

			<div class="media-body">
				<h2 class="media-heading">{{ quest.title }}</h2>
				<p>{{ quest.question }}</p>
			</div>

			{% for tag in quest.tags.all %}
				<a href="{% url 'ask:tag_view' tag.id %}" class="label label-info">{{ tag.name }}</a>
			{% endfor %}

			{% if user.is_authenticated %}
				<form method="post">
				{% csrf_token %}
					<div class="btn-group btn-group-xs pull-right">
						<button type="submit" class="btn btn-danger" name="question_dislike">
							<span class="glyphicon glyphicon-remove"></span>
						</button>

						<p class="btn btn-default" disabled>
							{{ quest.rating }}
						</p>

						<button type="submit" class="btn btn-success" name="question_like">
							<span class="glyphicon glyphicon-ok"></span>
						</button>
					</div>
				</form>
			{% else %}
				<div class="btn-group btn-group-xs pull-right">
					<p class="btn btn-default" disabled>
						{{ quest.rating }}
					</p>
				</div>
			{% endif %}
		</div>

		<hr>

		{% if answers %}
		<ul class="list-group">
			{% for answer in answers %}
				<li class="list-group-item">
					<div class="media">
						<a class="pull-left" href="{% url 'ask:user_questions' answer.author.id %}">
						{% if answer.author.avatar %}
			              <img class="media-object" src="{{ MEDIA_URL }}{{ answer.author.avatar }}" width="64" height="64">
			            {% else %}
			              <img width="64" height="64">
			            {% endif %}
						</a>

						<div class="media-body">
							<h2 class="media-heading">{{ answer.title }}</h2>
							<p>{{ answer.answer }}</p>
						</div>
						
						
						{% if user.is_authenticated and user.username == quest.author.username %}
							<form method="post">
								{% csrf_token %}
								<div class="btn-group btn-group-xs">
									{% if answer.right_answer %}
										<button type="submit" class="btn btn-success" name="wrong" value="{{ answer.id }}">
											Правильный ответ!
										</button>
									{% else %}
										<button type="submit" class="btn btn-info" name="right" value="{{ answer.id }}">
											Правильный ответ?
										</button>
									{% endif %}
								</div>
							</form>
						{% else %}
							<div class="btn-group btn-group-xs">
								{% if answer.right_answer %}
									<button class="btn btn-success">
										Правильный ответ!
									</button>
								{% endif %}
							</div>
						{% endif %}

						<div class="btn-toolbar pull-right">
						{% if user.is_authenticated %}
							<form method="post">
								{% csrf_token %}
								<div class="btn-group btn-group-xs">
									<button type="submit" class="btn btn-danger" name="answer_dislike" value="{{ answer.id }}">
										<span class="glyphicon glyphicon-remove"></span>
									</button>

									<p class="btn btn-default" disabled>
										{{ answer.rating }}
									</p>

									<button type="submit" class="btn btn-success" name="answer_like" value="{{ answer.id }}">
										<span class="glyphicon glyphicon-ok"></span>
									</button>
								</div>
							</form>
						{% else %}
							<div class="btn-group btn-group-xs">
								<p class="btn btn-default" disabled>
									{{ answer.rating }}
								</p>
							</div>
						{% endif %}
						</div>
					</div> <!-- media -->
				</li> <!-- list-group-item -->
			{% endfor %}
		</ul>

		<hr>
		{% endif %}

		{% if user.is_authenticated %}
			<form class="form-horizontal" role="form" method="post">
				{% csrf_token %}
				<div class="form-group">

					{% if form.answer.errors %}
			            <div class="alert alert-danger">
			              <button type="button" class="close" data-dismiss="alert">&times;</button>
			              {{ form.answer.errors }}
			            </div>
					{% endif %}

					<textarea class="form-control" style="resize: vertical;" rows="5"
			            id="{{ form.answer.id_for_label }}" 
			            name="{{ form.answer.name }}">{{ form.answer.value|default:'' }}</textarea>
				</div>

				<div class="form-group">
					<button type="submit" class="btn btn-success"> Ответить </button>
				</div>
			</form>
		{% endif %}
		
		<ul class="pager">
	      <li
	        {% if answers.has_previous %}
	          class="previous"><a href="?page={{ answers.previous_page_number }}"
	        {% else %}
	          class="previous disabled"><a
	        {% endif %}
	      > Назад </a></li>

	      <li
	        {% if answers.has_next %}
	          class="next"><a href="?page={{ answers.next_page_number }}"
	        {% else %}
	          class="next disabled"><a
	        {% endif %}
	      > Вперед </a></li>
	    </ul>
	{% endblock %}

ask_titaevskiy/templates/index.html
{% extends "base.html" %}

  {% block title %}
    {% if order = 'new' %}
      Последние вопросы
    {% else %}
      Популярные вопросы
    {% endif %}
  {% endblock %}

  {% block content %}
    {% block navigation %}
      <ul class="nav nav-pills">
        <li 
          {% if order = 'new' %}
            class="active"><a
          {% else %}
            ><a href="/"
          {% endif %}
        > Новые </a></li>

        <li
          {% if order = 'popular' %}
            class="active"><a
          {% else %}
            ><a href="?sort=popular"
          {% endif %}
        > Популярные </a></li>
      </ul>
    {% endblock navigation %}

    <ul class="list-group">

    {% for quest in quest_list %}
      <li class="list-group-item">
        <div class="media">
          <a class="pull-left" href="{% url 'ask:user_questions' quest.author.id %}">
            {% if quest.author.avatar %}
              <img class="media-object" src="{{ MEDIA_URL }}{{ quest.author.avatar }}" width="64" height="64">
            {% else %}
              <img width="64" height="64">
            {% endif %}
          </a>
          
          <div class="media-body">
            <a href="{% url 'ask:detail' quest.id %}"><h2 class="media-heading">{{ quest.title }}</h2></a>
            <p>{{ quest.question|truncatechars:300 }}</p>
          </div>

          {% for tag in quest.tags.all %}
            <a href="{% url 'ask:tag_view' tag.id %}" class="label label-info">{{ tag.name }}</a>
          {% endfor %}

          <div class="btn-toolbar pull-right">
            <div class="btn-group btn-group-xs">
              <p class="btn btn-primary" disabled><span class="glyphicon glyphicon-eye-open"></span></p>
              <p class="btn btn-default" disabled>{{ quest.views }}</p>
            </div>

            <div class="btn-group btn-group-xs">
              <p class="btn btn-primary" disabled><span class="glyphicon glyphicon-comment"></span></p>
              <p class="btn btn-default" disabled>{{ quest.answers.count }}</p>
            </div>

            <div class="btn-group btn-group-xs">
              <p class="btn btn-primary" disabled><span class="glyphicon glyphicon-bullhorn"></span></p>
              <p class="btn btn-default" disabled>{{ quest.rating }}</p>
            </div>
          </div>
        </div> <!-- media -->
      </li> <!-- list-group-item -->
    {% endfor %}

    </ul> <!-- list-group -->

    <ul class="pager">
      <li
        {% if quest_list.has_previous %}
          class="previous"><a href="?sort={{ order }}&amp;page={{ quest_list.previous_page_number }}"
        {% else %}
          class="previous disabled"><a
        {% endif %}
      > Назад </a></li>

      <li
        {% if quest_list.has_next %}
          class="next"><a href="?sort={{ order }}&amp;page={{ quest_list.next_page_number }}"
        {% else %}
          class="next disabled"><a
        {% endif %}
      > Вперед </a></li>
    </ul>
  {% endblock content %}

ask_titaevskiy/templates/new_question.html
{% extends "base.html" %}
  
  {% block title %}
    Новый вопрос
  {% endblock %}


  {% block include_css %}
    <link rel="stylesheet" type="text/css" href="/bootstrap-tokenfield/css/bootstrap-tokenfield.css">
  {% endblock %}

  {% block content %}
    <div class="page-header">
      <h1> Новый вопрос </h1>
    </div>

    <form class="form-horizontal" role="form" method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="{{ form.title.id_for_label }}" class="control-label col-md-2"> Заголовок </label>
        <div class="col-md-10">

        {% if form.title.errors %}
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ form.title.errors }}
          </div>
        {% endif %}

          <input type="text" class="form-control" id="{{ form.title.id_for_label }}"
            name="{{ form.title.name }}" value="{{ form.title.value|default:'' }}">
        </div>
      </div>

      <div class="form-group">
        <label for="{{ form.question.id_for_label }}" class="control-label col-md-2"> Вопрос </label>
        <div class="col-md-10">

          {% if form.question.errors %}
            <div class="alert alert-danger">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              {{ form.question.errors }}
            </div>
          {% endif %}

          <textarea class="form-control" rows="10" style="resize: vertical;" 
            id="{{ form.question.id_for_label }}" name="{{ form.question.name }}">{{ form.question.value|default:'' }}</textarea>
        </div>
      </div>

      <div class="form-group">
        <label for="{{ form.question.id_for_label }}" class="control-label col-md-2"> Теги </label>
        <div class="col-md-10">
          <input type="text" class="form-control" id="id_tags" name="tags">
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <button type="submit" class="btn btn-success"> Спросить </button>
        </div>
      </div>
    </form>
  {% endblock %}

  {% block include_js %}
    <script src="/bootstrap-tokenfield/bootstrap-tokenfield.min.js"></script>
  {% endblock %}

ask_titaevskiy/templates/popular_users.html
<a href='/user_questions/8' class='list-group-item'>
   sfuwtiwv
   <span class='badge'> 298 </span>
</a>
<a href='/user_questions/15' class='list-group-item'>
   rebxtgdc
   <span class='badge'> 281 </span>
</a>
<a href='/user_questions/10' class='list-group-item'>
   fuvyeigb
   <span class='badge'> 199 </span>
</a>
<a href='/user_questions/9' class='list-group-item'>
   qerzulib
   <span class='badge'> 189 </span>
</a>
<a href='/user_questions/11' class='list-group-item'>
   uyynzshq
   <span class='badge'> 175 </span>
</a>
<a href='/user_questions/14' class='list-group-item'>
   flbtyysf
   <span class='badge'> 166 </span>
</a>
<a href='/user_questions/7' class='list-group-item'>
   pqvveavj
   <span class='badge'> 159 </span>
</a>
<a href='/user_questions/12' class='list-group-item'>
   snpputno
   <span class='badge'> 154 </span>
</a>
<a href='/user_questions/17' class='list-group-item'>
   mpzvbydk
   <span class='badge'> 150 </span>
</a>
<a href='/user_questions/13' class='list-group-item'>
   ifjjfsuo
   <span class='badge'> 61 </span>
</a>

ask_titaevskiy/templates/signin.html
{% extends "base.html" %}

  {% block title %}
    Регистрация
  {% endblock %}

  {% block content %}
  <div class="page-header" id="new-question">
    <h1> Новый пользователь </h1>
  </div>

  <form class="form-horizontal" role="form" method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="{{ form.username.id_for_label }}" class="control-label col-md-2"> Логин </label>
      <div class="col-md-10">

      {% if form.username.errors %}
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          {{ form.username.errors }}
        </div>
      {% endif %}

        <input type="text" class="form-control" id="{{ form.username.id_for_label }}"
          name="{{ form.username.name }}" value="{{ form.username.value|default:'' }}">
      </div>
    </div>

    <div class="form-group">
      <label for="{{ form.email.id_for_label }}" class="control-label col-md-2"> Email </label>
      <div class="col-md-10">

      {% if form.email.errors %}
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          {{ form.email.errors }}
        </div>
      {% endif %}

        <input type="email" class="form-control" id="{{ form.email.id_for_label }}"
          name="{{ form.email.name }}" value="{{ form.email.value|default:'' }}">
      </div>
    </div>

    <div class="form-group">
      <label for="{{ form.password.id_for_label }}" class="control-label col-md-2"> Пароль </label>
      <div class="col-md-10">

      {% if form.password.errors %}
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          {{ form.password.errors }}
        </div>
      {% endif %}

        <input type="password" class="form-control" id="{{ form.password.id_for_label }}"
          name="{{ form.password.name }}" value="{{ form.password.value|default:'' }}">
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <button type="submit" class="btn btn-success"> Зарегистрироваться </button>
      </div>
    </div>
  </form>
  {% endblock content %}

ask_titaevskiy/templates/tag_view.html
{% extends "index.html" %}

  {% block title %}
      Тег: {{ tag.name }}
  {% endblock %}

  {% block navigation %}
  {% endblock navigation %}

ask_titaevskiy/templates/user_questions.html
{% extends "index.html" %}

  {% block title %}
  	{{ author.username }}
  {% endblock %}

  {% block navigation %}
  {% endblock navigation %}

ask_titaevskiy/templates/user_settings.html
{% extends "base.html" %}
  
  {% block title %}
    Мои настройки
  {% endblock %}

  {% block content %}
    <div class="page-header" id="new-question">
      <h1> Настройки </h1>
    </div>

    <form class="form-horizontal" role="form" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
        <label for="{{ form.username.id_for_label }}" class="control-label col-md-2"> Login </label>
        <div class="col-md-4">

          {% if form.username.errors %}
            <div class="alert alert-danger">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              {{ form.username.errors }}
            </div>
          {% endif %}

          <input type="text" class="form-control" id="{{ form.username.id_for_label }}"
            name="{{ form.username.name }}" value="{{ user.username }}">
        </div>
      </div>

      <div class="form-group">
        <label for="{{ form.email.id_for_label }}" class="control-label col-md-2"> Email </label>
        <div class="col-md-4">

          {% if form.email.errors %}
            <div class="alert alert-danger">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              {{ form.email.errors }}
            </div>
          {% endif %}

          <input type="email" class="form-control" id="{{ form.email.id_for_label }}"
            name="{{ form.email.name }}" value="{{ user.email }}">
        </div>
      </div>

      <div class="form-group">
        <label for="{{ form.avatar.id_for_label }}" class="control-label col-md-2"> Аватар </label>
        <div class="col-md-4">

          {% if form.avatar.errors %}
            <div class="alert alert-danger">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              {{ form.avatar.errors }}
            </div>
          {% endif %}

          <input type="file" id="{{ form.avatar.id_for_label }}"
            name="{{ form.avatar.name }}">
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <button type="submit" class="btn btn-info"> Сохранить </button>
        </div>
      </div>
    </form>
  {% endblock %}